function decode(m) {
    m = m.replace(/\\\/\\\//g, 'w')
    m = m.replace(/\/\\/g, 'a')
    m = m.replace(/\]3/g, 'b')
    m = m.replace(/\|\)/g, 'd')
    m = m.replace(/\[-/g, 'e')
    m = m.replace(/\/\=/g, 'f')
    m = m.replace(/\(\_\,/g, 'g')
    m = m.replace(/\|\-\|/g, 'h')
    m = m.replace(/\_\T/g, 'j')
    m = m.replace(/\/</g, 'k')
    m = m.replace(/\|.\/\|/g, 'm')
    m = m.replace(/\|\\\|/g, 'n')
    m = m.replace(/\(\)\_/g, 'q')
    m = m.replace(/\(\)/g, 'o')
    m = m.replace(/\|\^/g, 'p')
    m = m.replace(/\/\?/g, 'r')
    m = m.replace(/_\\~/g, 's')
    m = m.replace(/\~\|\~/g, 't')
    m = m.replace(/\|\_\|/g, 'u')
    m = m.replace(/\>\</g, 'x')
    m = m.replace(/\`\//g, 'y')
    m = m.replace(/\~\/\_/g, 'z')
    m = m.replace(/__/g, ' ')
    m = m.replace(/\|\_/g, 'l')
    m = m.replace(/\\\//g, 'v')
    m = m.replace(/\|/g, 'i')
    m = m.replace(/\(/g, 'c')
    m = [...m].map(x => x === m[0] ? '' : x).join('')

    return [...m].reverse().join('')
}